import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const proximaNova = localFont({
  src: [
    {
      path: "./fonts/ProximaNova-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/ProximaNova-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/ProximaNova-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/ProximaNova-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
});

const redHatDisplay = localFont({
  src: [
    {
      path: "./fonts/RedHatDisplay-Semibold.ttf",
      weight: "600",
      style: "normal",
    }
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
